# The URL the site will be built for
base_url = "https://codingezio.github.io"

# My essentials
title = "Rants and thoughts"
description = "Contact me via google_plus@aim.com"
default_language = "en"
minify_html = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "https://codingEzio.github.io",
    "https://github.com/codingEzio",
    "https://github.com/",
    "https://dev.mysql.com",
    "https://simplicable.com",
    "https://www.amazon.com",
    "https://www.rfcreader.com",
    "https://www.bcryptcalculator.com",
    "https://jwt.io",
    "https://docs.microsoft.com",
    "https://ankiweb.net",
    "https://stackoverflow.com",
    "https://askubuntu.com",
    "https://stackexchange.com",
    "https://superuser.com",
    "https://mariadb.org",
    "https://iherb.com",
    "https://auth0.com",
    "https://postman.com",
    "https://sdkman.io",
    "https://get.sdkman.io",
    "https://reddit.com",
    "https://old.reddit.com",
    "https://leetcode.cn",
    "https://gohugo.io",
    "https://acfun.iiilab.com/"
]

[extra]
# Put all your custom variables here

# Theme
# Lightspeed https://www.getzola.org/themes/lightspeed/
theme = "lightspeed"
