# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - run: git config --global --add safe.directory *
      - name: checkout
        uses: actions/checkout@v2
      - run: git config --global --add safe.directory /github/workspace
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          # Generated then add it to this repo (name)
          # TOKEN: ${{ secrets.TOKEN }}
          TOKEN: ${{ secrets.ZOLA }}
          # Or if publishing to the same repo, use the automatic token
          # It turns out this Github Action failed..
          # TOKEN: ${{ secrets.GITHUB_TOKEN }}
